### ISSUE TITLE
Simple Actor flag causes facial texture corruption and crashes

### ISSUE THREAD

**Issue by littlej541** [Perchik71/X-Cell-FO4#1]
### Versions:
F4SE Version: 0.6.23
X-Cell Version: 1.5-b65
Fallout 4 Version: 1.10.163

### Problem:
Facial texture corruption on actors with `Simple Actor` flag set and crashes when child actor has `Simple Actor` flag set and AI Processing (TAI command) is enabled.

### Description:
I first noticed this when I was crashing while approaching a child captive from the [Raider Children](https://www.nexusmods.com/fallout4/mods/16586) mod.

As a first step, I disabled X-Cell since it was one of the more recent mods I'd installed and it stopped crashing. When I enabled X-Cell again, I noticed that the actor had corrupted facial textures when viewed from afar. After investigating I found that the base actor for the face had the `Simple Actor` flag checked. Removing this flag fixed the texture and crash issue.

I then created a load order with no mods other than X-Cell and a test ESP I created with an actor that had the flag set. When I spawned the actor, the game did not crash but the face textures were still corrupted. Since it was crashing previously with a child actor, I added one to the test ESP and spawned it in. The game then crashed, but only if AI processing was enabled. Since the crash requires AI processing to be on and being near the child actor, I believe the crash has something to do with facial animations when speaking.

### Screenshots:
![ScreenShot41](https://github.com/user-attachments/assets/c3695015-4851-4950-be4d-1823d7366ba3)
![ScreenShot44](https://github.com/user-attachments/assets/1725aad7-2e54-435d-891e-7935189a33bf)

**Comment by Perchik71** [comment]
faces were not black for me, however, there was a crash, added to skip
